# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Dota2Guide")
        MainWindow.resize(471, 251)
        MainWindow.setMinimumSize(QtCore.QSize(471, 251))
        MainWindow.setMaximumSize(QtCore.QSize(471, 251))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"font-family: Arial Black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vibor_geroya = QtWidgets.QLabel(self.centralwidget)
        self.vibor_geroya.setGeometry(QtCore.QRect(43, 20, 178, 40))
        self.vibor_geroya.setStyleSheet("background-color:rgba(255,255,255,40)\n"
"")
        self.vibor_geroya.setObjectName("vibor_geroya")
        self.icon_vibor_geroya = QtWidgets.QLabel(self.centralwidget)
        self.icon_vibor_geroya.setEnabled(True)
        self.icon_vibor_geroya.setGeometry(QtCore.QRect(20, 20, 23, 40))
        self.icon_vibor_geroya.setMouseTracking(True)
        self.icon_vibor_geroya.setStyleSheet("background-color:rgba(255,255,255,40)\n"
"")
        self.icon_vibor_geroya.setText("")
        self.icon_vibor_geroya.setPixmap(QtGui.QPixmap(":/icons/icons/sensor_occupied_24dp_FILL0_wght400_GRAD0_opsz24.svg"))
        self.icon_vibor_geroya.setObjectName("icon_vibor_geroya")
        self.icon_vibor_roli = QtWidgets.QLabel(self.centralwidget)
        self.icon_vibor_roli.setGeometry(QtCore.QRect(250, 20, 23, 40))
        self.icon_vibor_roli.setStyleSheet("background-color:rgba(255,255,255,40)\n"
"")
        self.icon_vibor_roli.setText("")
        self.icon_vibor_roli.setPixmap(QtGui.QPixmap(":/icons/icons/radar_24dp_FILL0_wght400_GRAD0_opsz24.svg"))
        self.icon_vibor_roli.setObjectName("icon_vibor_roli")
        self.vibor_roli = QtWidgets.QLabel(self.centralwidget)
        self.vibor_roli.setGeometry(QtCore.QRect(273, 20, 178, 40))
        self.vibor_roli.setStyleSheet("background-color:rgba(255,255,255,40)\n"
"")
        self.vibor_roli.setObjectName("vibor_roli")
        self.hero_choose = QtWidgets.QComboBox(self.centralwidget)
        self.hero_choose.setGeometry(QtCore.QRect(20, 61, 201, 40))
        self.hero_choose.setObjectName("hero_choose")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.hero_choose.addItem("")
        self.rule_choose = QtWidgets.QComboBox(self.centralwidget)
        self.rule_choose.setGeometry(QtCore.QRect(250, 61, 201, 40))
        self.rule_choose.setObjectName("rule_choose")
        self.rule_choose.addItem("")
        self.rule_choose.addItem("")
        self.rule_choose.addItem("")
        self.rule_choose.addItem("")
        self.rule_choose.addItem("")
        self.rule_choose.addItem("")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(170, 120, 131, 51))
        self.confirm.setObjectName("confirm")

        self.rewatch = QtWidgets.QPushButton(self.centralwidget)
        self.rewatch.setGeometry(QtCore.QRect(360, 190, 91, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/refresh_24dp_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rewatch.setIcon(icon)
        self.rewatch.setObjectName("rewatch")
        self.last_hero = QtWidgets.QLabel(self.centralwidget)
        self.last_hero.setGeometry(QtCore.QRect(20, 190, 340, 41))
        self.last_hero.setStyleSheet("background-color:rgba(255,255,255,40)\n"
"")
        self.last_hero.setObjectName("last_hero")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dota2Guide"))
        MainWindow.setWindowIcon(QtGui.QIcon('dota_icon_project.png'))
        self.vibor_geroya.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">ВЫБЕРИ ГЕРОЯ</span></p></body></html>"))
        self.vibor_roli.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">ВЫБЕРИ РОЛЬ</span></p></body></html>"))
        self.hero_choose.setItemText(0, _translate("MainWindow", "Пусто"))
        self.hero_choose.setItemText(1, _translate("MainWindow", "Anti Mage"))
        self.hero_choose.setItemText(2, _translate("MainWindow", "Arc Warden"))
        self.hero_choose.setItemText(3, _translate("MainWindow", "Ember Spirit"))
        self.hero_choose.setItemText(4, _translate("MainWindow", "Hoodwing"))
        self.hero_choose.setItemText(5, _translate("MainWindow", "Marci"))
        self.hero_choose.setItemText(6, _translate("MainWindow", "Pudge"))
        self.hero_choose.setItemText(7, _translate("MainWindow", "Naga Siren"))
        self.hero_choose.setItemText(8, _translate("MainWindow", "Shadowfiend"))
        self.hero_choose.setItemText(9, _translate("MainWindow", "Slark"))
        self.hero_choose.setItemText(10, _translate("MainWindow", "Templar Assassin"))
        self.hero_choose.setItemText(11, _translate("MainWindow", "Void Spirit"))
        self.rule_choose.setItemText(0, _translate("MainWindow", "Пусто"))
        self.rule_choose.setItemText(1, _translate("MainWindow", "Мид"))
        self.rule_choose.setItemText(2, _translate("MainWindow", "Керри"))
        self.rule_choose.setItemText(3, _translate("MainWindow", "Оффлейнер"))
        self.rule_choose.setItemText(4, _translate("MainWindow", "Софт-Саппорт"))
        self.rule_choose.setItemText(5, _translate("MainWindow", "Фулл-Саппорт"))
        self.confirm.setText(_translate("MainWindow", "Подтверждение"))
        self.rewatch.setText(_translate("MainWindow", "Смотреть"))
        self.last_hero.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Последний герой: </span></p></body></html>"))





