# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 500)
        self.pickhero = QtWidgets.QComboBox(Dialog)
        self.pickhero.setGeometry(QtCore.QRect(20, 40, 100, 31))
        self.pickhero.setObjectName("pickhero")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickhero.addItem("")
        self.pickherotxt = QtWidgets.QLabel(Dialog)
        self.pickherotxt.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.pickherotxt.setObjectName("pickherotxt")
        self.pickrole = QtWidgets.QComboBox(Dialog)
        self.pickrole.setGeometry(QtCore.QRect(130, 40, 100, 31))
        self.pickrole.setObjectName("pickrole")
        self.pickrole.addItem("")
        self.pickrole.addItem("")
        self.pickrole.addItem("")
        self.pickrole.addItem("")
        self.pickherotxt_2 = QtWidgets.QLabel(Dialog)
        self.pickherotxt_2.setGeometry(QtCore.QRect(130, 10, 101, 31))
        self.pickherotxt_2.setObjectName("pickherotxt_2")
        self.konf = QtWidgets.QPushButton(Dialog)
        self.konf.setGeometry(QtCore.QRect(250, 40, 100, 31))
        self.konf.setObjectName("konf")
        self.konf.pressed.connect(self.vivod)
        self.guid = QtWidgets.QLabel(Dialog)
        self.guid.setGeometry(QtCore.QRect(20, 90, 340, 380))
        self.guid.setMinimumSize(QtCore.QSize(0, 0))
        self.guid.setText("")
        self.guid.setObjectName("guid")
        self.guidpicture = QtWidgets.QLabel(Dialog)
        self.guidpicture.setGeometry(QtCore.QRect(380, 90, 340, 380))
        self.guidpicture.setText("")
        self.guidpicture.setObjectName("guidpicture")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DOtA2 Guides"))
        self.pickhero.setItemText(0, _translate("Dialog", "None"))
        self.pickhero.setItemText(1, _translate("Dialog", "Anti-Mage"))
        self.pickhero.setItemText(2, _translate("Dialog", "Shadowfiend"))
        self.pickhero.setItemText(3, _translate("Dialog", "Arc Warden"))
        self.pickhero.setItemText(4, _translate("Dialog", "Slark"))
        self.pickhero.setItemText(5, _translate("Dialog", "Pudge"))
        self.pickhero.setItemText(6, _translate("Dialog", "Marci"))
        self.pickhero.setItemText(7, _translate("Dialog", "Ember Spirit"))
        self.pickhero.setItemText(8, _translate("Dialog", "Void Spirit"))
        self.pickhero.setItemText(9, _translate("Dialog", "Naga Siren"))
        self.pickherotxt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Выбор героя</span></p></body></html>"))
        self.pickrole.setItemText(0, _translate("Dialog", "Carry"))
        self.pickrole.setItemText(1, _translate("Dialog", "Mid"))
        self.pickrole.setItemText(2, _translate("Dialog", "Offlane"))
        self.pickrole.setItemText(3, _translate("Dialog", "Support"))
        self.pickherotxt_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Позиция</span></p></body></html>"))
        self.konf.setText(_translate("Dialog", "ок"))


    def vivod(self):
        a = self.pickhero.currentText()
        b = self.pickrole.currentText()
        if a == "Void Spirit" and b == "Mid":
            self.guid.setText(f"Основная роль Void Spirit в игре, это быть живучим инициатором \nдрак и вносить огромное количество быстрого урона по врагам."
                              "\nЭтот герой очень мобилен, имеет притяжку, может впитать \nурон щитом и может быть очень полезным на всех стадиях игры."
                              "\n\nСуть билда заключается в актуальности артефактов \nMANTA STYLE хорошо себя показывает как начальный артефакт"
                              "\nК томуже с MANTAой можно взять BOOTS OF TRAVEL а не PT \nтогда план на раннюю игру такой: Подрался, TP на базу, фарм \nЕсли же игра не задалась, то стоит взять PT + MAGE SLAYER"
                              "\n\nДалее идут слоты для тимфайта, например AGANIM SEPTER \nAS имеет сразу несколько аспектов полезных в тимфайте:"
                              "\n -массовое безмолвие которое можно использовать дважды \n -неплохой AOE урон \n -2 щита которые тем профитнее, чем больше врагов заденут"
                              "\nKAYA-SANGE имеет все необходимые VOIDу статы \nSHIVAS GUARD также помогает в тимфайте: \n -замедляя атаку и скорость врагов \n -повышая входящий урон"
                              "\n -уменьшая восстановление здоровья врагам \nBKB это ситуативный айтем, актуальный почти на каждом герое \n\nПод конец игры стоит докупить слоты на урон или на сейв"
                              "\n\nТаланты стоит брать: левый левый левый левый")
            pixmap = QPixmap("void2.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Void Spirit" and b == "Carry":
            self.guid.setText("Не стоит выбирать его в качестве керри")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Void Spirit" and b == "Support":
            self.guid.setText("Не стоит выбирать его в саппорта")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Void Spirit" and b == "Offlane":
            self.guid.setText(f"Основная роль Void Spirit в игре, это быть живучим инициатором \nдрак и вносить огромное количество быстрого урона по врагам."
                              "\nЭтот герой очень мобилен, имеет притяжку, может впитать \nурон щитом и может быть очень полезным на всех стадиях игры."
                              "\n\nПервый предмет на линию это всегда URN OF SHADOWS \nЗатем берется артефакт для тимфайта:MAGE SLAYER"
                              "\nС этими двумя артефактами ты уже неплохо дамажишь. \nПлан на раннюю игру заключается в роуме по карте\nЕсли же игра не задалась, то стоит взять MIDAS вместо URNы"
                              "\n\nДалее идут слоты для тимфайта, например: \nAGANIM имеющий важные аспекты полезные в тимфайте:"
                              "\n -массовое безмолвие которое можно использовать дважды \n -неплохой AOE урон \n -2 щита всегда лучше чем 1"
                              "\nKAYA-SANGE имеет все необходимые VOIDу статы \nSHIVAS GUARD также помогает в тимфайте: \n -замедляя атаку и скорость врагов \n -повышая входящий урон"
                              "\n -уменьшая восстановление здоровья врагам \nBKB это ситуативный айтем, актуальный почти на каждом герое \n\nПод конец игры стоит докупить слоты на урон или на сейв"
                              "\n\nТаланты стоит брать: левый левый левый левый")
            pixmap = QPixmap("void3.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Marci" and b == "Offlane":
            self.guid.setText(f"Основная роль Marci в игре, это быть инициатором драк\nнаносящим огромное количество урона и контроля по врагам."
                              "\nЭтот герой очень мобилен, имеет стан, много урона,\nпассивный бонус к вампиизму полезный на всех стадиях игры."
                              "\n\nПервый предмет на линию это всегда ORB OF CORROSION\nЗатем берется артефакт для тимфайта:BLADE MAIL"
                              "\nС этими двумя артефактами ты уже неплохо дерешься.\nПлан на раннюю игру заключается в роуме по карте\nили же целенапраленном навязывании драк на своей линии"
                              "\nЕсли же игра не задалась, то вместо ORBа взять MIDAS"
                              "\n\nДалее идут слоты для тимфайта, например:\nAGANIM имеющий важные аспекты полезные в тимфайте:"
                              "\n -массовое безмолвие во время ульты\n -уменьшение кулдауна ультиммейта\n -развеивание при применение ульты"
                              "\nBASHER хорош из за быстроты нанесения ударов\nSHARD дает возможность соло-кила и преследования"
                              "\nBKB это ситуативный айтем, актуальный почти всегда\n\nПод конец игры стоит докупить слот по ситуации\nНапример при нехватке урона можно взять DAEDALUS"
                              "\nа при нехватке выживаемости - LINKEN или WW"
                              "\n\nТаланты стоит брать: правый правый левый левый")
            pixmap = QPixmap("marciofflane.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Marci" and b == "Mid":
            self.guid.setText(f"Основная роль Marci в игре, это быть инициатором драк\nнаносящим огромное количество урона и контроля по врагам."
                              "\nЭтот герой очень мобилен, имеет стан, много урона,\nпассивный бонус к вампиизму полезный на всех стадиях игры."
                              "\n\nПервый предмет на линию после это всегда ORB OF CORROSION\nЗатем берется артефакт для тимфайта:DIFFUSAL BLADE"
                              "\nС этими двумя артефактами ты уже неплохо дерешься.\nПлан на раннюю игру заключается в демонтаже мид тавера\nа затем навязывании драк на сайд линиях"
                              "\nДраться по кд ульты, смок+2 сапа и вперед\nЕсли же игра не задалась, то вместо ORBа взять MIDAS"
                              "\n\nДалее идут слоты для тимфайта, например:\nAGANIM имеющий важные аспекты полезные в тимфайте:"
                              "\n -массовое безмолвие во время ульты\n -уменьшение кулдауна ультиммейта\n -развеивание при применение ульты"
                              "\nBASHER хорош из за быстроты нанесения ударов\nSHARD дает возможность соло-кила и преследования"
                              "\nBKB это ситуативный айтем, актуальный почти всегда\n\nПод конец игры стоит докупить слот по ситуации\nНапример при нехватке урона можно взять DAEDALUS"
                              "\nа при нехватке выживаемости - LINKEN или DISPERSER"
                              "\n\nТаланты стоит брать: правый правый левый левый")
            pixmap = QPixmap("marcimid.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Marci" and b == "Support":
            self.guid.setText(f"Основная роль Marci в игре, это быть инициатором драк\nнаносящим огромное количество урона и контроля по врагам."
                              "\nЭтот герой очень мобилен, имеет стан, много урона, а также\nпассивный бонус к вампиизму полезный на всех стадиях игры."
                              "\nХороший агрессивный сап, который хорош в роуме"
                              "\n\nПервый предмет на линию это всегда ORB OF CORROSION\nБотинок на выбор, смотря чего не хватает"
                              "\nЗатем берется либо BLINK DAGGER + SHARD на темп\nЛибо GLIMMER CAPE + AETHER LENS для сейва\nПлан на раннюю игру заключается в роуме по карте"
                              "\nЕсли игра не задалась, стоит сосредоточиться на сейв айтемах"
                              "\n\nДалее идут слоты для тимфайта, например:\nAGANIM имеющий важные аспекты полезные в тимфайте:"
                              "\n -массовое безмолвие во время ульты\n -уменьшение кулдауна ультиммейта\n -развеивание при применение ульты"
                              "\nDIFFUSAL хорош изза быстроты нанесения ударов в ульте\nLINKEN дает возможность сейвить тиммейтов или себя"
                              "\nBKB это ситуативный айтем, актуальный почти всегда\n\nПод конец игры стоит докупить слот по ситуации\nНапример при нехватке урона можно взять DAEDALUS"
                              "\nа при нехватке контроля - BLOTHTORN"
                              "\n\nТаланты стоит брать: правый правый левый левый")
            pixmap = QPixmap("marcisupport.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Marci" and b == "Carry":
            self.guid.setText(f"Не стоит пикать этого героя в керри")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Ember Spirit" and b == "Mid":
            self.guid.setText(f"Основная роль Ember Spirit в игре, это быть мобильным героем с\n потенциалом для затяжной драки, внося свой урон постепенно."
                              "\nЭтот герой очень мобилен, имеет связку, может впитать маг\nурон щитом и может быть очень полезным на всех стадиях игры."
                              "\n\nСуть билда заключается в инициации ранних драк \nв которые MAGE SLAYER и ORB могут внести ощутимый импакт"
                              "\nЗатем берется MAELSTORM для того что бы успевать в темп.\nПо игре план такой: подрался, ремнант, тп на базу, фарм\nЕсли игра не задалась, то стоит сосредоточится на сплите пачек"
                              "\n\nДалее идут слоты для тимфайта, например AGANIM SEPTER \nAS имеет сразу несколько аспектов полезных в тимфайте:"
                              "\n -больше ремнантов - значит большая мобильность \n -возможность быстро уйти из драки или зайти в нее"
                              "\nKAYA-SANGE имеет все необходимые EMBERу статы \nSHIVAS GUARD также помогает в тимфайте: \n -замедляя атаку и скорость врагов \n -повышая входящий урон"
                              "\n -уменьшая восстановление здоровья врагам \nBKB это ситуативный айтем, актуальный на каждом герое \n\nПод конец игры стоит докупить слоты на урон или на сейв"
                              "\n\nТаланты стоит брать: левый правый левый правый")
            pixmap = QPixmap("embermid.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Ember Spirit" and b == "Carry":
            self.guid.setText(f"Не стоит пикать этого героя в керри")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Ember Spirit" and b == "Offlane":
            self.guid.setText(f"Не стоит пикать этого героя в оффлейн")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Ember Spirit" and b == "Support":
            self.guid.setText(f"Не стоит пикать этого героя в саппорта")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Pudge" and b == "Carry":
            self.guid.setText(f"Не стоит пикать этого героя в керри")
            pixmap = QPixmap("rapira.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Pudge" and b == "Mid":
            self.guid.setText(f"Основная роль PUDGE в игре, это быть живучим героем с\n продолжительным, быстрым уроном и контролем файта."
                              "\nPUDGE может хукнуть врага, нарушив его позиционку,\n может впитывать много урона, а также хорошо гангать"
                              "\n\nСуть билда заключается в постепенном усилении героя \nСтоит взять ORB OF COROSION для доминации на линии"
                              "\nЗатем берется BLINK если лайнинг прошел удачно, \nили начать сразу с ETHERIAL BLADE для усиления прокаста\nЕсли игра не задалась, то стоит пойти в ганги на сайды"
                              "\n\nДалее идут слоты для тимфайта, например AGANIM SEPTER \nAS имеет сразу несколько аспектов полезных в тимфайте:"
                              "\n -усиление и без того большого урона \n -уменьшение восстановление хп врагам\n -радиус урона, замедления и дебафф аувеличивается в два раза"
                              "\nкупив AS необходимо купить SHROUD для маг резиста\nSHIVAS GUARD также помогает в тимфайте: \n -замедляя атаку и скорость врагов \n -повышая входящий урон"
                              "\n -уменьшая восстановление здоровья врагам \nBKB это ситуативный айтем, актуальный на каждом герое \n\nПод конец игры стоит докупить слоты на урон или на сейв"
                              "\n\nТаланты стоит брать: левый правый правый правый")
            pixmap = QPixmap("pudgemid.jpg")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Pudge" and b == "Offlane":
            self.guid.setText(f"Основная роль PUDGE в игре, это быть живучим героем с\n продолжительным, быстрым уроном и контролем файта."
                              "\nPUDGE может хукнуть врага, нарушив его позиционку,\n может впитывать много урона, а также хорошо гангать"
                              "\n\nСуть билда заключается в постепенном усилении героя \nСтоит взять ORB OF COROSION для доминации на линии"
                              "\nЗатем берется BLINK если лайнинг прошел удачно, \nили начать сразу с ETHERIAL BLADE для усиления прокаста\nЕсли игра не задалась, то стоит пойти в ганги на сайды"
                              "\n\nДалее идут слоты для тимфайта, например AGANIM SEPTER \nAS имеет сразу несколько аспектов полезных в тимфайте:"
                              "\n -усиление и без того большого урона \n -уменьшение восстановление хп врагам\n -радиус урона, замедления и дебафф аувеличивается в два раза"
                              "\nкупив AS необходимо купить SHROUD для маг резиста\nSHIVAS GUARD также помогает в тимфайте: \n -замедляя атаку и скорость врагов \n -повышая входящий урон"
                              "\n -уменьшая восстановление здоровья врагам \nBKB это ситуативный айтем, актуальный на каждом герое \n\nПод конец игры стоит докупить слоты на урон или на сейв"
                              "\n\nТаланты стоит брать: левый правый правый правый")
            pixmap = QPixmap("pudgeofflane.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Pudge" and b == "Support":
            self.guid.setText(f"Основная роль PUDGE в игре, это быть живучим героем с\n продолжительным, быстрым уроном и контролем файта."
                              "\nPUDGE может хукнуть врага, нарушив его позиционку,\n может впитывать много урона, а также хорошо гангать"
                              "\n\nСуть билда заключается в постепенном усилении героя.\nСапог берется в зависимости от кора и того, что ему нужно \nЗатем взять быстрый BLINK для комфортной игры"
                              "\nЕсли игра не задалась, стоит пойти помогать на другие линии"
                              "\n\nДалее идут слоты для тимфайта, например AGANIM SHARD \nAS имеет сразу важнейший для саппорта - сейв"
                              "\n -шард позволяет съесть тиммейта, отхилив его"
                              "\nкупив AS нужно купить AETHER LENS для лучшей позиционки\nFORCE STAFF помогает сейвить тиммейтов или себя\nPIPE берется против большого маг урона"
                              "\nBKB это ситуативный айтем, актуальный на каждом герое \n\nПод конец игры стоит докупить слоты на на сейв или живучесть"
                              "\n\nТаланты стоит брать: левый левый правый правый")
            pixmap = QPixmap("pudgesupport.png")
            self.guidpicture.setPixmap(pixmap)

        elif a == "Anti-Mage" and b == "Carry":
            self.guid.setText(f"Основная роль ANTI MAGE")
            pixmap = QPixmap("antimagecarry.png")
            self.guidpicture.setPixmap(pixmap)


















if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
